export const TOGAE_THEME = "TOGAE_THEME"

export const GET_CONTECT = "GET_CONTECT"
export const ADD_CONTECT = "ADD_CONTECT"
export const DELETE_CONTECT = "DELETE_CONTECT"
export const UPDATE_CONTECT = "UPDATE_CONTECT"
export const ERROR_CONTECT = "ERROR_CONTECT"





