export const LOADING_FACILITY = "LOADING_FACILITY"

export const GET_FACILITY = "GET_FACILITY"
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DICREMENT_COUNTER = "DICREMENT_COUNTER"
export const ADD_FACILITY = "ADD_FACILITY"
export const DELETE_FACILITY = "DELETE_FACILITY"
export const UPDATE_FACILITY = "UPDATE_FACILITY"


export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"


export const LOADING_SHOP = "LOADING_SHOP"
export const GET_SHOP = "GET_SHOP"
export const ADD_SHOP = "ADD_SHOP"



export const LOADING_REVIEW = "LOADING_REVIEW"
export const GET_REVIEW = "GET_REVIEW"
export const ADD_REVIEW = "ADD_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"


export const GET_COUPANCODE = "GET_COUPANCODE"
export const ADD_COUPANCODE = "ADD_COUPANCODE"
export const DELETE_COUPANCODE = "DELETE_COUPANCODE"
export const UPDATE_COUPANCODE = "UPDATE_COUPANCODE"
export const ERROR_COUPANCODE = "ERROR_COUPANCODE"


export const GET_CATEGORI = "GET_CATEGORI"
export const ADD_CATEGORI = "ADD_CATEGORI"
export const DELETE_CATEGORI = "DELETE_CATEGORI"
export const UPDATE_CATEGORI = "UPDATE_CATEGORI"
export const ERROR_CATEGORI = "ERROR_CATEGORI"

export const GET_VARIANT = "GET_VARIANT"
export const ADD_VARIANT = "ADD_VARIANT"
export const DELETE_VARIANT = "DELETE_VARIANT"
export const UPDATE_VARIANT = "UPDATE_VARIANT"
export const ERROR_VARIANT = "ERROR_VARIANT"


export const GET_SELSPEOPLE = "GET_SELSPEOPLE"
export const ADD_SELSPEOPLE = "ADD_SELSPEOPLE"
export const DELETE_SELSPEOPLE = "DELETE_SELSPEOPLE"
export const UPDATE_SELSPEOPLE = "UPDATE_SELSPEOPLE"
export const ERROR_SELSPEOPLE = "ERROR_SELSPEOPLE"